// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnBbL_FeZBa6sIM35yJLsKRnuTZLN82wQ',
    appId: '1:213817305123:web:ff0e7b4867515a00856996',
    messagingSenderId: '213817305123',
    projectId: 'fluttermovies-82e68',
    authDomain: 'fluttermovies-82e68.firebaseapp.com',
    storageBucket: 'fluttermovies-82e68.firebasestorage.app',
    measurementId: 'G-XH51MHKCBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIqjdlMOMxinZTh9k3Ay7vWayeaW4cFc8',
    appId: '1:213817305123:android:64406e52d9f3a042856996',
    messagingSenderId: '213817305123',
    projectId: 'fluttermovies-82e68',
    storageBucket: 'fluttermovies-82e68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBYhL1q6fDTSl3qZqIUIEvkaGTPqonLJo',
    appId: '1:213817305123:ios:12f265f66c50daf9856996',
    messagingSenderId: '213817305123',
    projectId: 'fluttermovies-82e68',
    storageBucket: 'fluttermovies-82e68.firebasestorage.app',
    iosBundleId: 'com.example.fluttermovies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBYhL1q6fDTSl3qZqIUIEvkaGTPqonLJo',
    appId: '1:213817305123:ios:12f265f66c50daf9856996',
    messagingSenderId: '213817305123',
    projectId: 'fluttermovies-82e68',
    storageBucket: 'fluttermovies-82e68.firebasestorage.app',
    iosBundleId: 'com.example.fluttermovies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnBbL_FeZBa6sIM35yJLsKRnuTZLN82wQ',
    appId: '1:213817305123:web:a3fdba90d99b7df6856996',
    messagingSenderId: '213817305123',
    projectId: 'fluttermovies-82e68',
    authDomain: 'fluttermovies-82e68.firebaseapp.com',
    storageBucket: 'fluttermovies-82e68.firebasestorage.app',
    measurementId: 'G-CW5HL2L1B6',
  );
}
